[package]
name = "ps-buffer"
description = "aligned heap buffer"
version = "0.1.0-12"
edition = "2021"
license = "GPL-3.0-or-later"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
ps-alloc = "0.1.0-4"
ps-range = "0.1.0-2"
thiserror = "2.0.12"
